trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_ROOT: '$(Agent.TempDirectory)/myapp'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: '18.10.x'

    - script: npm install -g @angular/cli
      displayName: 'Install Angular CLI'

    - script: |
        cd CoachAndFocus.Web.UI/ClientApp
        npm install
      displayName: 'Install npm dependencies'

    - script: |
        cd CoachAndFocus.Web.UI/ClientApp
        ng test --watch=false --browsers=ChromeHeadless
      displayName: 'Run Angular tests'

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.0.x'
        includePreviewVersions: true

    - script: dotnet build --configuration Release
      displayName: 'Build with dotnet'   
      
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'ChrisBrooksbankParly (e6ba8781-b352-41d3-acd1-2d969d978b38)'
    appType: 'webApp'
    WebAppName: 'coachandfocus'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
